version: "3.9"
services:
  node:
    # Build the Dockerfile in this directory.
    build: .
    # In case of a crash, restart this service.
    restart: unless-stopped
    # Start this service after the graphite service was started.
    depends_on:
      - "graphite"
  graphite:
    image: graphiteapp/graphite-statsd
    restart: unless-stopped
    volumes:
      - ./volumes/graphite/configs:/opt/graphite/conf
      - ./volumes/graphite/data:/opt/graphite/storage
      - ./volumes/statsd_config:/opt/statsd/config
    ports:
      # Port for sending data to StatsD.
      - "8125:8125/udp"
      # Port for viewing Graphite in the browser or to connect to Grafana.
      - "8080:8080"
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"

